#!/usr/bin/env python3
'''
List all the compositions.
'''
from pprint import pprint

# Get basic connection to fusion. 
fu = bmd.scriptapp("Fusion")
#pprint( dir(fu) )

compList = fu.GetCompList().values()
for comp in compList:
    # get all Composition attributes and print a couple that are of interest.
    compAttrs = comp.GetAttrs()
    compName = compAttrs["COMPS_Name"]
    compFile = compAttrs["COMPS_FileName"]
    pprint( f'Name: {compName},  File: {compFile}' )
    #pprint( compAttrs )
    '''
    {'COMPB_HiQ': True,
    'COMPB_Locked': False,
    'COMPB_LoopPlay': True,
    'COMPB_Modified': False,
    'COMPB_MotionBlur': True,
    'COMPB_Proxy': False,
    'COMPB_Rendering': False,
    'COMPI_RenderFlags': 131072.0,
    'COMPI_RenderStep': 1.0,
    'COMPN_AudioOffset': 0.0,
    'COMPN_AverageFrameTime': 0.0,
    'COMPN_CurrentTime': 0.0,
    'COMPN_ElapsedTime': 0.0,
    'COMPN_GlobalEnd': 1000.0,
    'COMPN_GlobalStart': 0.0,
    'COMPN_LastFrameRendered': -2000000000.0,
    'COMPN_LastFrameTime': 0.0,
    'COMPN_RenderEnd': 1000.0,
    'COMPN_RenderEndTime': 1000.0,
    'COMPN_RenderStart': 0.0,
    'COMPN_RenderStartTime': 0.0,
    'COMPN_TimeRemaining': 0.0,
    'COMPS_FileName': '/Volumes/VideoScratch/VideoProjects/test2.comp',
    'COMPS_LoopMode': 'loop',
    'COMPS_Name': 'test2.comp'}
    '''
    # Get all composition FrameFormat preferences.
    compPrefs = comp.GetPrefs()['Comp']['FrameFormat']
    frameFormatGuideRatio  = compPrefs['GuideRatio']
    frameFormatHeight      = compPrefs['Height']
    frameFormatName        = compPrefs['Name']
    frameFormatRate        = compPrefs['Rate']
    frameFormatWidth       = compPrefs['Width']
    pprint( f'Composition Name: {compName}')
    pprint( f'            File: {compFile.strip()}' )
    pprint( f'          Format: {frameFormatName}' )
    pprint( f'                  {frameFormatWidth}x{frameFormatHeight}' )
    pprint( f'                  {frameFormatRate}fps' )
    pprint( f'                  {frameFormatGuideRatio}' )
    #pprint( compPrefs )
    '''
    {'Comp': 
        {'AVI': 
            {'Saver': 
                {'DataCheck': True,
                            'DataRate': 300.0,
                            'Handler': 541215044.0,
                            'Key': 15.0,
                            'KeyCheck': True,
                            'Quality': 75.0
                }
            },
          'Audio': {'Playback': True},
          'AutoSave': {'Delay': 600.0, 'Enabled': True, 'OnRender': True},
          'Bins': {'LoaderBin': '<none>', 'SaverBin': '<none>'},
          'ChildFrame': {1.0: {'Mode': 3.0,
                               'OpenOnNew': True,
                               'UseWindowsDefaults': True}},
          'Cluster': {'RenderRange': 1.0,
                      'SideFrames': 10.0,
                      'SlaveClasses': 'all'},
          'DiskCache': {'CacheLoaders': {'DiskCache': True,
                                         'Enable': True,
                                         'LimitedSize': False,
                                         'MaxSize': 200.0,
                                         'MultiFrame': True,
                                         'NoLocal': True,
                                         'OnMissingOrig': 0.0,
                                         'Separator': '!'},
                        'NetGroups': 'all'},
          'FilterModeName': '<unknown>',
          'FlowView': {'AspectTilePics': True,
                       'AutoSnap': True,
                       'ConnectedSnap': False,
                       'Direction': 0.0,
                       'ForceActive': False,
                       'ForceAll': False,
                       'ForceMask': False,
                       'ForceModes': True,
                       'ForceSource': False,
                       'FullToolIndicator': False,
                       'GridSnap': False,
                       'PipeStyle': 1.0,
                       'PipesOnTop': False,
                       'RemoveRouters': True,
                       'Scale': 1.0,
                       'ShowGrid': True,
                       'ShowHidden': False,
                       'ShowInstanceLinks': True,
                       'ShowNavigator': 2.0,
                       'ShowThumbnails': True},
          'FrameForamt': {'GuidRatio': 1.77777777777778,
                          'Height': 1080.0,
                          'Name': 'HD 1080',
                          'Rate': 23.97,
                          'Width': 1920.0},
          'FrameFormat': {'AspectLoader': 0.0,
                          'AspectX': 1.0,
                          'AspectY': 1.0,
                          'DepthFull': 3.0,
                          'DepthInteractive': 0.0,
                          'DepthLoader': 0.0,
                          'DepthLock': False,
                          'DepthPreview': 1.0,
                          'DropFrame': 0.0,
                          'Fields': False,
                          'GuidRatio': 1.77777777777778,
                          'GuideRatio': 1.77777777777778,
                          'GuideX1': 0.0,
                          'GuideX2': 1.0,
                          'GuideY1': 0.0,
                          'GuideY2': 1.0,
                          'Height': 1080.0,
                          'Name': 'HD 1080',
                          'PerFeet': 1.0,
                          'Rate': 23.97,
                          'TimeCodeRadio': 1.0,
                          'TimeCodeType': 0.0,
                          'Width': 1920.0},
          'FreehandLUTPrecDlg': {'Window': {'Left': 756.0, 'Top': 135.0}},
          'FreehandPrecDlg': {'Window': {'Left': 0.0, 'Top': 88.0}},
          'Import': {'EDL': {'FlowFormat': 0.0, 'UseShotNames': 0.0}},
          'Info': {'Author': '',
                   'Client': '',
                   'Comments': '',
                   'CreateDate': '',
                   'Job': '',
                   'ModifyDate': ''},
          'Interactive': {'BackgroundRender': False,
                          'Proxy': {'Auto': False,
                                    'AutoScale': 8.0,
                                    'Scale': 4.0},
                          'SelectiveUpdate': 1.0},
          'LUTView': {'AutoScaleVal': 1.0,
                      'IndependentHandles': False,
                      'ShowKeyMarkers': False,
                      'ShowTips': False},
          'LastFile': '/Applications/Visual Studio Code.app',
          'LastLUTFile': '',
          'Memory': {'FramesAtOnce': 2.0,
                     'Interactive': {'ResponseTime': 0.5,
                                     'SimultaneousBranching': False},
                     'Render': {'SimultaneousBranching': False}},
          'Network': {'DoNetworkRenders': False, 'SlaveMemOverride': False},
          'NumberStyles': {'ClipFrame': 0.0, 'Color': 0.0},
          'Paths': {'EnableReverseMapping': False},
          'PolyKeyListDlg': {'Window': {'Left': -1.0, 'Top': -1.0}},
          'Preview': {'ActiveLoaders': True,
                      'ActiveSavers': True,
                      'Depth': 0.0,
                      'Height': 160.0,
                      'HiQ': True,
                      'KeepAspect': True,
                      'OutputDevice': 'Left.A',
                      'Scale': True,
                      'SizeType': 1.0,
                      'SkipFrames': False,
                      'Type': 1.0,
                      'Width': 200.0},
          'QuickTime': {'Compressor': 'Apple ProRes 422 LT_apcs',
                        'DataCheck': False,
                        'DataRate': 1000.0,
                        'KeyCheck': True,
                        'KeyRate': 30.0,
                        'Quality': 75.0},
          'SplineEditor': {'AutoScale': False,
                           'AutoScaleVal': 1.0,
                           'AutoSnap': {'Guides': 1.0, 'Keys': 2.0},
                           'FollowActive': False,
                           'IndependentHandles': False,
                           'ShowKeyMarkers': False,
                           'ShowTips': True},
          'Splines': {'AutoSmoothBSplinePolylines': True,
                      'AutoSmoothBSplines': True,
                      'AutoSmoothLUTs': False,
                      'AutoSmoothMeshes': True,
                      'AutoSmoothPaths': False,
                      'AutoSmoothPolylines': False,
                      'AutoSmoothSplines': False,
                      'BSplineDegree': 3.0,
                      'BSplinePolylineDegree': 3.0,
                      'DefOnionSkinCount': 10.0,
                      'DefOnionSkinRange': 3.0,
                      'DefOnionSkinStep': 5.0,
                      'ExportMode': 16.0,
                      'OnionSkinAnchor': False,
                      'OnionSkinClickSetCT': False,
                      'OnionSkinPointPlot': False,
                      'OnionSkinShowHull': True,
                      'PolyLineEditMode': 'InsertAndModify',
                      'RotoAssist': False,
                      'RotoAssistDistance': 8.0,
                      'RotoAssistMultiplePts': False,
                      'RotoAssistTracking': False,
                      'SelectPointsFromMultiPolies': True,
                      'TrackerPath': 'PolyPath',
                      'TrackerPointsShow': 2.0},
          'Timeline': {'AutoSnap': {'Guides': -1.0, 'Keys': 2.0},
                       'ViewFilterMode': -1.0},
          'Transport': {'FrameStep': 1.0},
          'Tweaks': {'CloneOverlayBlend': 0.6,
                     'CloneOverlayMethod': 0.0,
                     'DisableFlowReordering': False,
                     'GPU': {'Caching': 2.0, 'Enable': 1.0}},
          'Unsorted': {'GlobalEnd': 1000.0, 'GlobalStart': 0.0},
          'UserInterface': {'SelectionSync': True},
          'Views': {'Defaults': {'3DHistogram': {'DrawStyles': 0.0,
                                                 'Log': False,
                                                 'LoopLines': True,
                                                 'Proxy': 4.0,
                                                 'Transparent': True},
                                 'AlwaysOnTop': True,
                                 'BgColor': -1.0,
                                 'BufferLUT': {'Enable': False,
                                               'Plugin': 'FusionViewLUT',
                                               'Selected': ''},
                                 'CheckerUnderlay': False,
                                 'Controls': {'Autofade': False,
                                              'FadeDelay': 2000.0,
                                              'FadeSpeed': 1.0,
                                              'Hiding': 0.0,
                                              'Opacity': 100.0,
                                              'SnapPixel': False,
                                              'SnapPixelMode': 0.0,
                                              'StippleHidden': True},
                                 'Dither': False,
                                 'FullScreen': False,
                                 'Guides': {'Center': True,
                                            'Film': False,
                                            'FrameAspect': 'Default',
                                            'SafeImage': True,
                                            'SafeTitle': True,
                                            'Show': False},
                                 'Histogram': {'Channels': 7.0,
                                               'DrawStyles': 0.0,
                                               'Scale': 0.0,
                                               'Transparent': False},
                                 'MaterialViewer': {'Camera': {'Rotation': {'X': 15.0,
                                                                            'Y': -20.0,
                                                                            'Z': 0.0}},
                                                    'Options': {'LightPosition': 0.0,
                                                                'LightingEnabled': True,
                                                                'RendererType': 'RendererOpenGL',
                                                                'SurfaceType': 0.0,
                                                                'TextureDepth': 'int8'}},
                                 'Mirror': {'Device': '',
                                            'Enable': False,
                                            'StereoMethod': 'Auto'},
                                 'OpToolbar': {'Size': 0.0, 'Style': 0.0},
                                 'PickH': 1.0,
                                 'PickW': 1.0,
                                 'PrevCtrlActiveColor': 4278190335.0,
                                 'PrevCtrlInactiveColor': 4278255360.0,
                                 'QuadLayoutName': '4-Way',
                                 'QuadView': False,
                                 'ShowClipFrameNumbers': True,
                                 'Stereo': {'ABSource': False,
                                            'AnaglyphColor': 'Red/Cyan',
                                            'AnaglyphMethod': 'Color',
                                            'DisplayMethod': 'Quad Buffer',
                                            'Enabled': False,
                                            'OffsetX': {'QuadB': 0.0,
                                                        'Stack': 0.0},
                                            'OffsetY': {'QuadB': 0.0,
                                                        'Stack': 0.0},
                                            'Stack': False,
                                            'StackMethod': 'Horizontal',
                                            'Swap': False},
                                 'SubView': {'Enabled': False,
                                             'ID': 'GLHistogramViewer',
                                             'Magnifier': False,
                                             'MagnifierScale': 8.0,
                                             'Navigator': False},
                                 'Toolbar': {'Size': 0.0, 'Style': 0.0},
                                 'Vectorscope': {'Color': False,
                                                 'ColorSpace': 0.0,
                                                 'DrawStyles': 1.0,
                                                 'LoopLines': True,
                                                 'OneLine': False,
                                                 'SubSampling': 4.0},
                                 'VideoOut': False,
                                 'View3D': {'CamFront': {'Position': {'X': 0.0,
                                                                      'Y': 0.0,
                                                                      'Z': 0.0},
                                                         'Rotation': {'X': 0.0,
                                                                      'Y': 0.0,
                                                                      'Z': 0.0},
                                                         'Scale': 1.0},
                                            'CamLeft': {'Position': {'X': 0.0,
                                                                     'Y': 0.0,
                                                                     'Z': 0.0},
                                                        'Rotation': {'X': 0.0,
                                                                     'Y': 90.0,
                                                                     'Z': 0.0},
                                                        'Scale': 1.0},
                                            'CamPersp': {'Position': {'X': 0.0,
                                                                      'Y': 0.0,
                                                                      'Z': 0.0},
                                                         'Rotation': {'X': 30.0,
                                                                      'Y': 0.0,
                                                                      'Z': 0.0},
                                                         'Scale': 1.0},
                                            'CamRight': {'Position': {'X': 0.0,
                                                                      'Y': 0.0,
                                                                      'Z': 0.0},
                                                         'Rotation': {'X': 0.0,
                                                                      'Y': -90.0,
                                                                      'Z': 0.0},
                                                         'Scale': 1.0},
                                            'CamTop': {'Position': {'X': 0.0,
                                                                    'Y': 0.0,
                                                                    'Z': 0.0},
                                                       'Rotation': {'X': 90.0,
                                                                    'Y': 0.0,
                                                                    'Z': 0.0},
                                                       'Scale': 1.0},
                                            'CameraName': 'Perspective',
                                            'CustomOverscan': 1.37,
                                            'Options': {'Culling': False,
                                                        'DefaultLight': True,
                                                        'Grid': True,
                                                        'Lighting': False,
                                                        'SelectionBoxStipple': 65520.0,
                                                        'SelectionBoxStippleHidden': 52416.0,
                                                        'Shadows': False,
                                                        'ShowCameras': True,
                                                        'ShowFastLabel': False,
                                                        'ShowLights': True,
                                                        'ShowMatteObjects': False,
                                                        'ShowPointClouds': True,
                                                        'ShowTextureMemory': False,
                                                        'ShowUVTangentVectors': False,
                                                        'ShowVertexNormals': False,
                                                        'Wireframe': False},
                                            'OverscanMode': 0.0,
                                            'SortMethod': 'ZBuffer',
                                            'TextureDepth': 'int8'},
                                 'Viewer': {'AlphaOverlay': False,
                                            'Channel': -1.0,
                                            'CheckerUnderlay': True,
                                            'DoD': {'Show': False},
                                            'EnableLUTs': False,
                                            'FarZ': -1000.0,
                                            'FitMarginX': 0.0,
                                            'FitMarginY': 0.0,
                                            'FollowActive': False,
                                            'ID': 'GLImageViewer',
                                            'LUTPlugin': 'FusionViewLUT',
                                            'LUTSelected': '',
                                            'Layer': '',
                                            'NearZ': 0.0,
                                            'Normalise': False,
                                            'One2One': False,
                                            'OverlayColor': 7.0,
                                            'OverlayOpacity': 100.0,
                                            'PixelGrid': False,
                                            'Region': {'Auto': False,
                                                       'Bottom': 0.0,
                                                       'Enable': False,
                                                       'Left': 0.0,
                                                       'Lock': False,
                                                       'Right': 1.0,
                                                       'Show': True,
                                                       'Top': 1.0},
                                            'ScaleMode': 0.0,
                                            'ShowControls': True,
                                            'ShowLabels': True,
                                            'Smooth': True,
                                            'SmoothThreshold': 1000000.0,
                                            'View360': 0.0},
                                 'Waveform': {'ColorSpace': 0.0,
                                              'LoopLines': True,
                                              'Mode': 0.0,
                                              'OneLine': False,
                                              'SubSampling': 4.0}},
                    'Left': {'PickH': 1.0,
                             'PickW': 1.0,
                             'PrevCtrlActiveColor': 4278190335.0,
                             'PrevCtrlInactiveColor': 4278255360.0,
                             'RulersShow': True,
                             'SideB': {'PickH': 1.0,
                                       'PickW': 1.0,
                                       'PrevCtrlActiveColor': 4278190335.0,
                                       'PrevCtrlInactiveColor': 4278255360.0,
                                       'Viewer': {'EnableLUTs': False,
                                                  'FarZ': -1000.0,
                                                  'FitMarginType': 0.0,
                                                  'FitMarginX': 0.0,
                                                  'FitMarginY': 0.0,
                                                  'LUTPlugin': 'FusionViewLUT',
                                                  'NearZ': 0.0}},
                             'Viewer': {'EnableLUTs': False,
                                        'FarZ': -1000.0,
                                        'FitMarginType': 0.0,
                                        'FitMarginX': 0.0,
                                        'FitMarginY': 0.0,
                                        'LUTPlugin': 'FusionViewLUT',
                                        'NearZ': 0.0}},
                    'LeftView': {'PickH': 1.0, 'PickW': 1.0},
                    'Right': {'PickH': 1.0,
                              'PickW': 1.0,
                              'PrevCtrlActiveColor': 4278190335.0,
                              'PrevCtrlInactiveColor': 4278255360.0,
                              'RulersShow': True,
                              'SideB': {'PickH': 1.0,
                                        'PickW': 1.0,
                                        'PrevCtrlActiveColor': 4278190335.0,
                                        'PrevCtrlInactiveColor': 4278255360.0,
                                        'Viewer': {'EnableLUTs': False,
                                                   'FarZ': -1000.0,
                                                   'FitMarginType': 0.0,
                                                   'FitMarginX': 0.0,
                                                   'FitMarginY': 0.0,
                                                   'LUTPlugin': 'FusionViewLUT',
                                                   'NearZ': 0.0}},
                              'Viewer': {'EnableLUTs': False,
                                         'FarZ': -1000.0,
                                         'FitMarginType': 0.0,
                                         'FitMarginX': 0.0,
                                         'FitMarginY': 0.0,
                                         'LUTPlugin': 'FusionViewLUT',
                                         'NearZ': 0.0}},
                    'RightView': {'PickH': 1.0,
                                  'PickW': 1.0,
                                  'View3D': {'CamFront': {'Position': {'X': 0.0,
                                                                       'Y': 0.0,
                                                                       'Z': 0.0},
                                                          'Rotation': {'X': 0.0,
                                                                       'Y': 0.0,
                                                                       'Z': 0.0},
                                                          'Scale': 1.0},
                                             'CamLeft': {'Position': {'X': 0.0,
                                                                      'Y': 0.0,
                                                                      'Z': 0.0},
                                                         'Rotation': {'X': 0.0,
                                                                      'Y': 90.0,
                                                                      'Z': 0.0},
                                                         'Scale': 1.0},
                                             'CamPersp': {'Position': {'X': 0.0,
                                                                       'Y': 0.0,
                                                                       'Z': 0.0},
                                                          'Rotation': {'X': 30.0,
                                                                       'Y': 0.0,
                                                                       'Z': 0.0},
                                                          'Scale': 1.0},
                                             'CamRight': {'Position': {'X': 0.0,
                                                                       'Y': 0.0,
                                                                       'Z': 0.0},
                                                          'Rotation': {'X': 0.0,
                                                                       'Y': -90.0,
                                                                       'Z': 0.0},
                                                          'Scale': 1.0},
                                             'CamTop': {'Position': {'X': 0.0,
                                                                     'Y': 0.0,
                                                                     'Z': 0.0},
                                                        'Rotation': {'X': 90.0,
                                                                     'Y': 0.0,
                                                                     'Z': 0.0},
                                                        'Scale': 1.0},
                                             'CameraName': 'Perspective'}},
                    'View1': {'PickH': 0.0,
                              'PickW': 0.0,
                              'PrevCtrlActiveColor': 0.0,
                              'PrevCtrlInactiveColor': 0.0,
                              'SideB': {'PickH': 1.0,
                                        'PickW': 1.0,
                                        'PrevCtrlActiveColor': 4278190335.0,
                                        'PrevCtrlInactiveColor': 4278255360.0,
                                        'Viewer': {'EnableLUTs': False,
                                                   'FarZ': -1000.0,
                                                   'FitMarginType': 0.0,
                                                   'FitMarginX': 0.0,
                                                   'FitMarginY': 0.0,
                                                   'LUTPlugin': 'FusionViewLUT',
                                                   'NearZ': 0.0}},
                              'Viewer': {'EnableLUTs': False,
                                         'FarZ': -1000.0,
                                         'FitMarginType': 0.0,
                                         'FitMarginX': 0.0,
                                         'FitMarginY': 0.0,
                                         'LUTPlugin': 'FusionViewLUT',
                                         'NearZ': 0.0}},
                    'View3D': {'DefLight': {'Ambient': {'Intensity': 0.15},
                                            'Directional': {'Intensity': 0.85,
                                                            'Position': 0.0}},
                               'FitToView': {'All': 1.0, 'Selected': 0.75},
                               'Grid': {'Antialiasing': False,
                                        'Axes': {'Color': 4280492835.0,
                                                 'Enable': True,
                                                 'Width': 2.0},
                                        'Major': {'Color': 4280492835.0,
                                                  'Enable': True,
                                                  'Spacing': 2.0,
                                                  'Width': 1.0},
                                        'Minor': {'Color': 4283453520.0,
                                                  'Enable': True,
                                                  'Spacing': 0.25,
                                                  'Width': 1.0},
                                        'Scale': 1.0,
                                        'Size': 24.0},
                               'Orthographic': {'AdaptiveFar': False,
                                                'AdaptiveNear': False,
                                                'Far': 100000.0,
                                                'Near': -100000.0},
                               'Perspective': {'AdaptiveFar': False,
                                               'AdaptiveNear': False,
                                               'ConvergenceDistance': 2.5,
                                               'EyeSeparation': 0.075,
                                               'Far': 100000.0,
                                               'FovY': 45.0,
                                               'Near': 0.05,
                                               'StereoMode': 'OffAxis',
                                               'StereoRigEye': 'Center'}}}}}
    '''
